version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3308
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=myapp
    command: >
      sh -c "npm run migration:run && npm run start:prod"

  db:
    image: mysql:8
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=myapp
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 